### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by paleo** [antonmedv/monkberry#52]
The build with Webpack 4 fails:

    ERROR in ./path/to/MyTemplate.monk
    Module build failed: TypeError: Cannot read property 'monkberry' of undefined
        at Object.exports.getLoaderConfig (/path/to/myproject/node_modules/monkberry-loader/node_modules/loader-utils/index.js:124:37)
        at Object.module.exports (/path/to/myproject/node_modules/monkberry-loader/src/index.js:6:28)

In `package.json`, the section `dependencies`:

    "monkberry": "4.0.8",
    "monkberry-directives": "4.0.8",
    "monkberry-events": "4.0.8",
    "monkberry-loader": "4.0.8",

**Comment by antonmedv** [comment]
I know, I'm working on next version: see next branch.

**Comment by paleo** [comment]
OK. Can we use the `next` branch now? Or is it still too unstable?

**Comment by antonmedv** [comment]
Still in dev. Actually I got monkberry-loader to work correctly with webpack4, try update.

**Comment by paleo** [comment]
> Actually I got monkberry-loader to work correctly with webpack4, try update.

With which version? I have the _4.0.8_. I don't see any commit or any npm release related to Webpack 4…

**Comment by antonmedv** [comment]
Yes, sorry. Fixed only in https://github.com/monkberry/monkberry-loader/releases/tag/3.8.2

**Comment by paleo** [comment]
With:

    "monkberry": "4.0.8",
    "monkberry-directives": "4.0.8",
    "monkberry-events": "4.0.8",
    "monkberry-loader": "3.8.2",
    "ts-loader": "3.5.0",
    "typescript": "2.7.2",
    "webpack": "4.1.0",
    "webpack-cli": "2.0.10"

The new error:

    ERROR in ./frontend/main.ts
    Module build failed: TypeError: Cannot read property 'ts' of undefined
        at getLoaderOptions (/path/to/myproject/node_modules/ts-loader/dist/index.js:70:44)
        at Object.loader (/path/to/myproject/node_modules/ts-loader/dist/index.js:23:19)
     @ multi ./frontend/main.ts

**Comment by paleo** [comment]
Sorry, there is still an error:

    ERROR in ./path/to/MyTemplate.monk
    Module build failed: TypeError: compiler.addSource is not a function
        at Object.module.exports (/path/to/myproject/node_modules/monkberry-loader/src/index.js:16:12)

With:

    "monkberry": "4.0.8",
    "monkberry-directives": "4.0.8",
    "monkberry-events": "4.0.8",
    "monkberry-loader": "3.8.2",
    "webpack": "4.1.0",
    "webpack-cli": "2.0.10"

**Comment by antonmedv** [comment]
Yes, "4.0.8" does not supports "3.8.2". There is no fix now. Sorry. But you can port in from "3.8.2".

**Comment by paleo** [comment]
Ah yes, I understand. But the directives are not available with Monkberry 3.8.2?

**Comment by antonmedv** [comment]
No.

**Comment by antonmedv** [comment]
But I think fixing 4.0.8 for work with wp4 is simple.

**Comment by paleo** [comment]
Here: https://github.com/monkberry/monkberry-loader/pull/2

**Comment by paleo** [comment]
Could you publish the npm package? It works like a charm on my project (66 templates) with Webpack 3 and 4. NB: I don't use the options `globals` neither `transforms`.

**Comment by antonmedv** [comment]
done

**Comment by paleo** [comment]
Thank you!
