### ISSUE TITLE
How to render template by name (name has string type)?

### ISSUE THREAD

**Issue by pikhovkin** [antonmedv/monkberry#54]
How to render template by name (name has string type)?
I need to pass the name of the template as a string.

Example:
```
<script type="text/monkberry" id="Template">
	<h1>Hello {{ name }}!</h1>
</script>

var view = Monkberry.render('Template', document.body); // <-- 'Template'
view.update({name: 'World'});
```

**Comment by antonmedv** [comment]
https://github.com/monkberry/standalone

**Comment by pikhovkin** [comment]
@antonmedv, example, please

**Comment by antonmedv** [comment]
Read the docs

**Comment by pikhovkin** [comment]
I didn't find this in docs. I would not ask if it was there.

**Comment by antonmedv** [comment]
Define template with text/monkberry.
```
<script type="text/monkberry" id="component">
    <h1>
        Hello, {{ name }}!
    </h1>
</script>
```
And you now can get access to component template.

`var view = Monkberry.render(component, document.body);`

**Comment by DeLaGuardo** [comment]
@pikhovkin templates in monkberry-standalone evaluated in global scope. So you can render them with little trick: `var view = Monkberry.render(window['Template'], document.body);` If you need to identify them by strings

**Comment by pikhovkin** [comment]
@DeLaGuardo, exactly! Thanks!
